In [12]:
import numpy as np
import torch

In [29]:
o = np.random.rand(2040, 1)
m = np.random.rand(32, 5, 2)

In [10]:
m[:, :1]

array([[0.27427466],
       [0.04620082],
       [0.51199911],
       ...,
       [0.68830039],
       [0.61052884],
       [0.64568668]])

In [22]:
torch.tensor(m[:, 1:].reshape(-1, 2)).flatten(1)

tensor([[0.8678, 0.0418],
        [0.8971, 0.5304],
        [0.3174, 0.1337],
        ...,
        [0.8195, 0.4436],
        [0.8303, 0.8601],
        [0.2153, 0.3906]], dtype=torch.float64)

In [24]:
np.concatenate((m[:, :1], m[:, 1:]), axis=1).shape

(2040, 2)

In [30]:
m[:, :, 0]

array([[3.66254009e-01, 5.91807301e-01, 2.74572847e-01, 7.58112315e-01,
        1.41325178e-01],
       [2.95602818e-01, 7.55092922e-01, 3.91895928e-01, 2.77800273e-01,
        4.05781573e-01],
       [6.94857537e-01, 5.62283534e-01, 9.82220966e-01, 8.31103545e-01,
        5.90788059e-01],
       [3.74728921e-01, 4.34779489e-01, 6.75052429e-01, 4.24384591e-01,
        5.88764925e-01],
       [9.74670157e-01, 8.98482551e-01, 5.51771990e-01, 5.24263055e-04,
        4.24599946e-01],
       [7.19325750e-01, 7.16737537e-02, 4.10391533e-01, 3.44565477e-01,
        4.47876793e-01],
       [7.26540035e-01, 2.93369914e-01, 4.85953752e-01, 4.57193763e-01,
        8.16395149e-01],
       [5.17665817e-01, 3.35761890e-01, 9.40244975e-01, 8.54050132e-01,
        7.11095444e-01],
       [1.43300816e-01, 5.54696727e-01, 7.51772028e-01, 1.48269026e-03,
        3.75193745e-01],
       [3.04983008e-01, 5.76382092e-01, 5.05095206e-01, 6.44669046e-01,
        8.01621556e-01],
       [3.14824923e-01, 2.0170